name = "sonnet-api"
compatibility_date = "2024-01-01"

# Configure static assets
[site]
bucket = "."

# Configure build output directory
[build]
command = ""

# Configure functions directory
[build.upload]
format = "service-worker"

[[redirects]]
from = "/v1/*"
to = "/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
